version: '3.8'

services:
  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - frontend

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
